apiVersion: v1
kind: Service
metadata:
  name: service-nodeport-web
  namespace: production
spec:
  type: NodePort       ## type du service
  ports: 
    - targetPort: 8080              ## port exposé en interne dans le cluster
      port: 8080             ## le port sur lequel les containers écoutent
      nodePort: 30008        ## Port d'accès (limité ~ 30 000 pour nodePort)
  selector:
    app: web
